type: "subconfig"
token: "Ymtia2JrYmtia2JrYmtiaxUtdLzrldhHtlcjc1Cwfo1u99rVk5HGe8EjT761brGtKm3H4Ran78rWl85HwzfRgw=="

exporter:
  queue:
    logs_batch_size: 2
    metrics_batch_size: 2
    traces_batch_size: 5

default:
  processor:
    - name: "license_checker/common"
      config:
        enabled: true
        expire_time: 4084665444
        tolerable_expire: 2h
        number_nodes: 200
        tolerable_num_ratio: 1.5

    # attribute_config: attribute 属性配置
    - name: "attribute_filter/app"
      config:
        cut:
          - predicate_key: "attributes.db.system"
            max_length: 1024
            match:
              - "mysql"
              - "postgresql"
              - "elasticsearch"
            keys:
              - "attributes.db.statement"
          - predicate_key: "attributes.db.system"
            max_length: 512
            match:
              - "redis"
              - "mangodb"
            keys:
              - "attributes.db.statement"
        drop:
          - predicate_key: "attributes.db.system"
            match:
              - "mysql"
              - "postgresql"
              - "elasticsearch"
            keys:
              - "attributes.db.statement"
          - predicate_key: "attributes.db.system"
            match:
              - "redis"
              - "mangodb"
            keys:

    - name: "apdex_calculator/fixed"
      config:
        calculator:
          type: "fixed"
          apdex_status: "satisfied"
        rules:
          - kind: ""
            metric_name: "bk_apm_duration"
            destination: "apdex_type_subconfig1"

    - name: "traces_deriver/delta"
      config:
        operations:
          - type: "delta"
            metric_name: "bk_apm_count"
            publish_interval: "10s"
            gc_interval: "1h"
            max_series: 1000
            rules:
              - kind: "SPAN_KIND_SERVER"
                predicate_key: ""
                dimensions:
                  - "resource.bk.instance.id"
                  - "span_name"
                  - "kind"
                  - "status.code"
                  - "resource.service.name"
                  - "resource.service.version"
                  - "resource.telemetry.sdk.name"
                  - "resource.telemetry.sdk.version"
                  - "resource.telemetry.sdk.language"
                  - "attributes.peer.service"

#    - name: "rate_limiter/token_bucket"
#      config:
#        type: token_bucket
#        qps: 100
#        burst: 200

service:
  - id: "Go-Tier-Name"
    processor:
      - name: "apdex_calculator/fixed"
        config:
          calculator:
            type: "fixed"
            apdex_status: "tolerating"
          rules:
            - kind: ""
              metric_name: "bk_apm_duration"
              destination: "apdex_type_subconfig2"
instance:
  - id: "golang:Go-Tier-Name:MANDOCHEN-MB0:192.168.1.5:8004"
    processor:
      - name: "apdex_calculator/fixed"
        config:
          calculator:
            type: "fixed"
            apdex_status: "frustrated"
          rules:
            - kind: ""
              metric_name: "bk_apm_duration"
              destination: "apdex_type_subconfig3"
